#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH --reservation=uppmax2022-2-5_6
#SBATCH -t 00:15:00
#SBATCH -J 05fastqc_out
#SBATCH --mail-type=ALL
#SBATCH --mail-user sybilherreraf@gmail.com

# Load modules
module load bioinfo-tools
module load FastQC

fastqc \
 /home/syhe3484/Sybil/GenomeAnalysis/data/raw_data/genomics_data/Illumina/*.fq.gz \
 --outdir=/home/syhe3484/Sybil/GenomeAnalysis/analyses/05_preprocessing/pre_trimming_fastqc  
